### ISSUE TITLE
Security Resources (Educate)

### ISSUE THREAD

**Issue by misterdai** [RisingStack/protect#9]
Like the idea of this project, would certainly help a lot of developers get started on better footer with security aspects.  I think it'd be useful if this module also provided suggestions and resources to encourage better security practises as well.  That way a developer can be educated on other areas of security that may not be within the realm of this module, or requires more custom code, as well as suggestions of alternatives (un-biased) that are probably a better idea to use if budgets are available and scale requires.

* Provide a list of important security aspects that this module doesn't (and won't) cover, with recommendations.  Such as: Password hashing (bcrypt, scrypt etc...), session rotation, cookie signing...
* Possibly recommend investigation of WAFs (Web Applicaiton Firewalls), if budgets allow or hosting provides (AWS for example).
* Other database injections like nosql based ones.  https://zanon.io/posts/nosql-injection-in-mongodb

Not suggesting a huge amount of information, but a few links to useful resources can always help educate any developers using the module :)

**Comment by gergelyke** [comment]
Great idea @misterdai ! What would you add? Do you have a few links which you'd like to see?

**Comment by misterdai** [comment]
Thanks :) How about something like the following that I threw together?

---

## Security Recommendations

### Other Aspects

There are plenty of other areas that you should be concerned about when it comes to security, that this module doesn't cover (yet or won't) for various reasons.  Here are a few that are worth researching:

* [Password Hashing](https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet)
  * Bcrypt modules: [bcrypt](https://www.npmjs.com/package/bcrypt),[bcryptjs](https://www.npmjs.com/package/bcryptjs), [bcrypt-as-promised](https://www.npmjs.com/package/bcrypt-as-promised) 
  * Scrypt modules: [scrypt](https://www.npmjs.com/package/scrypt), [scryptsy](https://www.npmjs.com/package/scryptsy), [scrypt-async](https://www.npmjs.com/package/scrypt-async)
* [NoSQL Injection](https://www.owasp.org/index.php/Testing_for_NoSQL_injection)
* [Session management](https://www.owasp.org/index.php/Session_Management_Cheat_Sheet)
* [CSRF - Cross Site Request Forgery](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet)
  * [CSURF Express Module](https://www.npmjs.com/package/csurf)
* Signed Cookies: [cookie-parser Express Module](https://expressjs.com/en/resources/middleware/cookie-parser.html)

### Resources

* [OWASP -Open Web Application Security Project](https://www.owasp.org/index.php/Main_Page)
* [Express: Production Best Practices](https://expressjs.com/en/advanced/best-practice-security.html)
* [RisingStack: Node.js Security Checklist](https://blog.risingstack.com/node-js-security-checklist/)

### Dedicated WAF

If you have the resources available (budget or hosting environment), a dedicated WAF (Web Application Firewall) can offer a robust solution to various security issues, such as blocking potential attackers and flagging their activity.

* [OWASP WAF information](https://www.owasp.org/index.php/Web_Application_Firewall)
* Hosting providers:
  * [AWS WAF](https://aws.amazon.com/waf/)
  * [Microsoft Azure WAF](https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-web-application-firewall-overview)
* [ModSecurity]() - Apache, nginX and other web servers.
* [CloudFlare](https://www.cloudflare.com/) - External WAF features.

**Comment by gergelyke** [comment]
looks good! can you send a PR please?
